Feature/arreglo front
Chek97/Gestion-Notas pull request #9
Opened 2021-03-01 08:49 UTC by CrisMendez

Termine el arreglo del front-end resta unicamente la paginacion y estaria listo para empezar las pruebas

2021-03-04 07:27 UTC, Chek97 requested changes

2021-03-04 07:27 UTC, Chek97 commented on Config/DBconfig.php
> +    define('DATABASE', 'pruebas');//cambiarlo
Si cambias el nombre de la base de datos todos la tendran igual, debes dejarla igual antes de hacer un merge
```suggestion
    define('DATABASE', 'gestionMaria');//cambiarlo
```

2021-03-04 07:27 UTC, Chek97 commented on Model/conexion.php
> +				$conexion = new PDO('mysql:host=localhost; dbname=pruebas', 'root', '');
Volvemos a lo mismo del archivo de conexiones, manten los nombres de la base de datos igual antes de hacer merge

2021-03-07 06:59 UTC, CrisMendez commented
Arreglados los conflictos

2021-03-08 06:55 UTC, Chek97 commented on View/Notes/showComments.php
> +>>>>>>> develop
esto no deberia estar, pero como no afecta lo dejare

2021-03-08 06:56 UTC, Chek97 approved these changes

2021-03-08 06:57 UTC, merged

2021-03-08 07:28 UTC, Chek97 commented on View/Reports/indexReports.php
> +		<nav aria-label="..."><!--Crear navegacion-->
Has quitado la paginacion y devolviste el codigo a un estado anterior